---
title: "Base Visuals"
author: "Austin Eaton"
date: "4/17/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# import libraries
library(tidyverse)
library(plyr)
library(GGally)
library(ggridges)
library(ggthemes)
library(ggpubr)
library(patchwork)
# import file
df <- read_csv('../NBAdraft.csv')

names(df)[8] <- "FG_college_perc"
names(df)[11] <- "2P_perc"
names(df)[14] <- "3P_perc"
names(df)[17] <- "FT_perc"
```

```{r message=FALSE, warning=FALSE}
## Top Schools ----
image <- count(df,'School') %>% 
  arrange(freq) %>% 
  tail(n=20) %>%
  mutate(School=factor(School, levels=School)) %>%
  ggplot( aes(x=School, y=freq)) + 
  geom_segment(
    aes(x=School, xend=School, y=0, yend=freq),
    color='grey',
    # color=ifelse(School == c("Kentucky"), "orange", "grey"),
    # size=ifelse(School %in% c("Kentucky"), 1.3, 0.7)
    ) +
  geom_point(size = 3, color='orange') +
  coord_flip() +
  theme_classic() +
  xlab("School") +
  ylab("Number of Draft Picks") +
  labs(title = "Where are most draft picks coming from?",
        subtitle = "Top 20 universities that have contributed players to the NBA draft since 2010.",
        caption = "Years: 2010-2021") +
  annotate("text", x="Duke", y=29+1.2, 
           label="Kentucky leads the pack!", 
           color='darkorange', size=3 , angle=0, fontface="bold", hjust=1)

# ggsave(file="top_schools.png", plot=image)
```


```{r message=FALSE, warning=FALSE}
## BOX PLOTS ----
par(mfrow = c(2,2))
a<-ggplot(df, aes(x=lottery, y=PTS_college, fill=lottery)) +
  geom_violin() +
  geom_boxplot(fill='white',width=0.3,color="black", alpha=0.7) +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  theme_classic() +
  theme(legend.position = "none") + # remove legend
  ylab("") +
  ggtitle("Points Scored per Game") +
  xlab("Lottery")
  
b<-ggplot(df, aes(x=lottery, y=MP_college, fill=lottery)) +
  geom_violin() +
  geom_boxplot(fill='white',width=0.3,color="black", alpha=0.7) +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  theme_classic() + 
  theme(legend.position = "none") + # remove legend
  ylab("") +
  ggtitle("Minutes Played per Game") +
  xlab("Lottery")

c<-ggplot(df, aes(x=lottery, y=FG_college_perc, fill=lottery)) +
  geom_violin() +
  geom_boxplot(fill='white',width=0.3,color="black", alpha=0.7) +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  theme_classic() + 
  theme(legend.position = "none") + # remove legend
  ylab("") +
  ggtitle("Field Goal Accuracy") +
  xlab("Lottery")

d<-ggplot(df, aes(x=lottery, y=`3P_perc`, fill=lottery)) +
  geom_violin() +
  geom_boxplot(fill='white',width=0.3,color="black", alpha=0.7) +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  theme_classic() + 
  theme(legend.position = "none") + # remove legend
  ylab("") +
  ggtitle("3 Point Accuracy") +
  xlab("Lottery")

e<-ggplot(df, aes(x=lottery, y=`2P_perc`, fill=lottery)) +
  geom_violin() +
  geom_boxplot(fill='white',width=0.3,color="black", alpha=0.7) +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  theme_classic() + 
  theme(legend.position = "none") +
  ylab("") +
  ggtitle("2 Point Accuracy") +
  xlab("Lottery")

f<-ggplot(df, aes(x=lottery, y=FT_perc, fill=lottery)) +
  geom_violin() +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  geom_boxplot(fill='white',width=0.3,color="black", alpha=0.7) +
  theme_classic() + 
  theme(legend.position = "none") +
  ylab("") +
  ggtitle("Free Throw Accuracy") +
  xlab("Lottery") 

g<-ggplot(df, aes(x=lottery, y=PF, fill=lottery)) +
  geom_violin() +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  geom_boxplot(fill='white',width=0.3,color="black", alpha=0.7) +
  theme_classic() + 
  theme(legend.position = "none") +
  ylab("") +
  ggtitle("Personal Fouls per Game") +
  xlab("Lottery") 

h<-ggplot(df, aes(x=lottery, y=AST_college, fill=lottery)) +
  geom_violin() +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  geom_boxplot(fill='white',width=0.3,color="black", alpha=0.7) +
  theme_classic() + 
  theme(legend.position = "none") +
  ylab("") +
  ggtitle("Assists per Game") +
  xlab("Lottery") 

i<-ggplot(df, aes(x=lottery, y=STL, fill=lottery)) +
  geom_violin() +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9")) +
  geom_boxplot(fill='white',width=0.3,color="black", alpha=0.7) +
  theme_classic() + 
  theme(legend.position = "none") +
  ylab("") +
  ggtitle("Steals per Game") +
  xlab("Lottery")

a+b+c+d+e+f+g+h+i+plot_layout(ncol = 3)
# figure <- ggarrange(a,b,c,d,
#                     # labels = c("Points Scored per Game", "Minutes Played per Game", "Field Goal Accuracy", "3 Point Accuracy"),#, "2 Point Accuracy", "Free Throw Accuracy"),
#                     nrow = 2, ncol=2)
# figure
# ggsave(file="boxplots.png", plot=figure)
ggsave(
  file="boxplots.png",
  plot = last_plot(),
  device = NULL,
  path = NULL,
  scale = 1.5,
  width = NA,
  height = NA,
  units = c("in", "cm", "mm", "px"),
  dpi = 300,
  limitsize = TRUE,
  bg = NULL
)
```

```{r}
## CORRELATION MATRIX ----

df.subset <- df[c('PTS_college',"2P_perc","3P_perc","FT_perc")]
ggcorr(df.subset, method = c("everything", "pearson"))
```

```{r}
## AVERAGE POINT PER GAME VS DRAFT PICK----
# points <- df$PTS_college
# draft.pick <- df$Pk

image <- ggplot(df, aes(x=Pk, y=PTS_college)) +
  geom_point(
    aes(color=lottery),#, shape=lottery),
    size=2,
    alpha=0.8,
  ) +
  scale_color_manual(
    values = c("#386cb0", "#fdb462", "#7fc97f")
  ) +
  geom_smooth(method = lm, col='red') + # add linear trend line
  theme_classic() +
  xlab("Draft Pick") +
  ylab("Average Points Per Game (college)") +
  ggtitle("Comparing points scored to draft pick number") +
  labs(title = "Points Scored for per Draft Pick",
        subtitle = "Comparing a player's average points per game to their draft number.",
        caption = "Years: 2010-2021")
image
ggsave(file="pointsPerGame_draft.png", plot=image)
```

```{r}
## SMALL MULTIPLES----
df.subset <- df[c('Pk',"2P_perc","3P_perc","FT_perc")]
df.percent <- df.subset %>% pivot_longer(!Pk, names_to = "PointType", values_to = "Percent")

library(ggridges)
ggplot(df.percent, aes(x = Percent, y = PointType, fill = PointType)) +
  geom_density_ridges() +
  theme_bw() +
  scale_y_discrete(labels=c("FT_perc" = "Free Throw", "3P_perc" = "3-Pointer", "2P_perc" = "2-Pointer")) + # change y-tick labels
  xlab("Percent Accuracy") +
  ylab("Type of Shot Attempted") +
  ggtitle("(Add Title Here)") +
  theme(legend.position = "none") # remove legend
```

```{r}
## RIDGELINE PLOT(SMALL MULTIPLES) ----
df.subset2 <- df[c('lottery',"2P_perc","3P_perc","FT_perc", "FG_college_perc")]
df.percent2 <- df.subset2 %>% pivot_longer(!lottery, names_to = "PointType", values_to = "Percent")

ggplot(df.percent2, aes(x = Percent, y = PointType, fill = PointType)) +
  geom_density_ridges() +
  facet_grid(lottery ~ .) +
  theme_classic() +
  scale_y_discrete(labels=c("FT_perc" = "Free Throw", "3P_perc" = "3-Pointer", "2P_perc" = "2-Pointer", "FG_college_perc" = "Field Goal")) + # change y-tick labels
  # scale_fill_manual(values=c("#999999", "#E69F00#981717", "#56B4E9", "red")) +
  scale_fill_manual(values=c("#f9c852", "#E69F00", "#dfbb85", "#bbbbbb")) +
  xlab("Percent Accuracy") +
  ylab("Type of Shot Attempted") +
  ggtitle("Comparing Point Stats of Lottery Choices") +
  theme(legend.position = "none") # remove legend

```


```{r}
## BUBBLE CHART----
## 
ggplot(df, aes(x=Pk, y=PTS_college, size=MP_college, color=lottery)) +
  geom_point(
    aes(color=lottery),#, shape=lottery),
    size=2,
    alpha=0.8,
  ) +
  scale_color_manual(
    values = c("#386cb0", "#fdb462", "#7fc97f")
  ) +
  geom_smooth(method = lm, col='red') + # add linear trend line
  theme_bw() +
  xlab("Draft Pick") +
  ylab("Average Points Per Game (college)") +
  ggtitle("Comparing points scored to draft pick number") + 
  scale_size(range = c(.1, 24), name="Population (M)")

ggplot(df, aes(x=Pk, y=PTS_college, size=FG_college_perc, color=lottery)) +
    geom_point(alpha=0.5) +
    scale_size(range = c(.1, 10), name="FG_college_perc")
```

```{r}
df.lotteryT <- df[which(df$lottery == "TRUE"),]

ggplot(df.lotteryT, aes(x = PTS_college)) +
  geom_boxplot(fill="#ff7f00") +
  facet_grid(Pk ~ .) +
  # theme_bw() +
  theme_classic() +
  xlab("Points Scored") +
  ggtitle("Average Points Scored vs. Draft Pick") +
  # theme(legend.position = "none") + # remove legend
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())


ggplot(df.lotteryT, aes(x = ORB)) +
  geom_boxplot(fill="#0080ff") +
  facet_grid(Pk ~ .) +
  # theme_bw() +
  theme_classic() +
  xlab("Average Offensive Rebounds") +
  ggtitle("Average Offensive Rebounds vs. Draft Pick") +
  # theme(legend.position = "none") + # remove legend
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())


ggplot(df.lotteryT, aes(x = DRB)) +
  geom_boxplot(fill="#808080") +
  facet_grid(Pk ~ .) +
  # theme_bw() +
  theme_classic() +
  xlab("Average Defensive Rebounds") +
  ggtitle("Average Defensive Rebounds vs. Draft Pick") +
  # theme(legend.position = "none") + # remove legend
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())


ggplot(df.lotteryT, aes(x = PF)) +
  geom_boxplot(fill="#ff0000") +
  facet_grid(Pk ~ .) +
  # theme_bw() +
  theme_classic() +
  xlab("Average Defensive Rebounds") +
  ggtitle("Average Defensive Rebounds vs. Draft Pick") +
  # theme(legend.position = "none") + # remove legend
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```
```{r}
ggplot(df, aes(x = PTS_college)) +
  geom_boxplot(aes(color=lottery)) +
  facet_grid(lottery ~ .) +
  # theme_bw() +
  theme_classic() +
  xlab("Points Scored") +
  ggtitle("Average Points Scored vs. Draft Pick") +
  # theme(legend.position = "none") + # remove legend
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  scale_fill_manual(values=c("#999999", "#E69F00"))

ggplot(df, aes(x=PTS_college, fill=lottery)) +
  # geom_violin() +
  geom_boxplot(width=0.3,color="#dfbb85", alpha=1) +
  scale_fill_manual(values=c("#999999", "#E69F00")) +
  theme_bw() + 
  xlab("")

```

```{r}
# Boxplot by group
ggplot(data = df, aes(x = feed, y = weight)) +
       stat_boxplot(geom = "errorbar", # Boxplot with error bars 
                    width = 0.2) +
       geom_boxplot(fill = "#4271AE", colour = "#1F3552", # Colors
                    alpha = 0.9, outlier.colour = "red") +
       scale_y_continuous(name = "Weight") +  # Continuous variable label
       scale_x_discrete(name = "Feed") +      # Group label
       ggtitle("Boxplot by groups ggplot2") + # Plot title
       theme(axis.line = element_line(colour = "black", # Theme customization
                                      size = 0.25))

p <- ggplot(df, aes(x = dose, y = len)) + 
  geom_boxplot(aes(fill = supp), position = position_dodge(0.9)) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800"))
```

Top variables:
GS,MP_college,two_P_perc,three_P,FTA,ORB,STL,SOS

